suppressMessages({library(Seurat)})
obj <- readRDS("data/GSE272719_neurons.clustered.rds")
md <- obj@meta.data
md$barcode_full <- rownames(md)
md$cluster <- as.character(Idents(obj))
um <- Embeddings(obj, "umap"); colnames(um) <- c("UMAP_1","UMAP_2")
out <- cbind(md, um[rownames(md), ])
write.csv(out, "data/neurons_clustered_metadata.csv", row.names = FALSE)
cat("assays:", Assays(obj), "\n"); cat("dims:", dim(obj), "\n")
cat("columns:", colnames(md), "\n")
print(head(rownames(md), 3)); print(head(rownames(obj), 5))
print(table(md$species, md$sex))
writeLines(rownames(obj[["RNA"]]), "data/rds_genes.txt")
cat("n genes:", nrow(obj[["RNA"]]), "\n")
